### PR TITLE
Unittest improvements

### PR DESCRIPTION
**Pull request by hille721**
As showed in #2 the tool currently does not work with Python version <= 3.8. To see such issues in the future, we have to do some unittesting (currently nothing)

### CODE REVIEW

**Comment by hille721** [comment]
adding pylint to our test pipeline (see https://github.com/hille721/simple-photo-gallery-bulkcreation/pull/4/commits/a01d4f7d0ea87ca37fb8532ef7c3a475ad278e09) already indicates, that we need at least Python 3.8 (#2,#3):

```
=================================== FAILURES ===================================
_______________ [pylint] src/simplegallery_bulkcreation/core.py ________________
E: 97, 4: Unexpected keyword argument 'dirs_exist_ok' in function call (unexpected-keyword-arg)
___________ [pylint] src/simplegallery_bulkcreation/galleryclass.py ____________
E:112, 8: Unexpected keyword argument 'dirs_exist_ok' in function call (unexpected-keyword-arg)
E:117, 8: Unexpected keyword argument 'dirs_exist_ok' in function call (unexpected-keyword-arg)

**Comment by hille721** [comment]
with https://github.com/hille721/simple-photo-gallery-bulkcreation/pull/4/commits/2e7d2fa057c2228e4a4ba188887c523195367a94 we also run tests on MacOS and Windows to ensure compatibility. And it works:

https://github.com/hille721/simple-photo-gallery-bulkcreation/runs/3808606986
